#!/bin/bash 
echo "Generating ANTARESS doc files"

MAKE_PATH=`pwd`
echo "$MAKE_PATH"
if [ "$MAKE_PATH" = "/builds/bourrier/antaress/Docs" ]
then
  DIR_PATH="/builds/bourrier/antaress"
else
  DIR_PATH="/Users/bourrier/Travaux/ANTARESS/Main"
fi

#Create rst files from py files in src/antaress/
echo "  From py files in src/antaress"
sphinx-apidoc --force -o "$DIR_PATH/Docs/source/" "$DIR_PATH/src/antaress/"


#Create rst files from py files in src/antaress/ANTARESS_* directories
for file in `find $DIR_PATH/src/antaress -type d -name "ANTARESS_*"`
do
  echo "  From py files in $file"
  sphinx-apidoc --force -o "$DIR_PATH/Docs/source/" "$file"
done

#Generate html files
make clean html
