#!/bin/bash 
echo "Generating ANTARESS doc files"

#Create rst files from py files in Method/
echo "  From py files in Method"
if [[ "$(pwd)" = "/builds/bourrier/antaress/Docs"]]
then
  DIR_PATH = /builds/bourrier/antaress/
fi
  
sphinx-apidoc --force -o DIR_PATH/Docs/source/ DIR_PATH/Method/

#Create rst files from py files in Method/ANTARESS_* directories
for file in `find DIR_PATH/Method -type d -name "ANTARESS_*"`
do
  echo "  From py files in $file"
  sphinx-apidoc --force -o DIR_PATH/Docs/source/ "$file"
done

#Generate html files
make clean html
