#!/bin/bash 
echo "Generating ANTARESS doc files"

#Create rst files from py files in Method/
echo "  From py files in Method"
sphinx-apidoc --force -o /Users/bourrier/Travaux/ANTARESS/Docs/source/ /Users/bourrier/Travaux/ANTARESS/Method/

#Create rst files from py files in Method/ANTARESS_* directories
for file in `find /Users/bourrier/Travaux/ANTARESS/Method -type d -name "ANTARESS_*"`
do
  echo "  From py files in $file"
  sphinx-apidoc --force -o /Users/bourrier/Travaux/ANTARESS/Docs/source/ "$file"
done

#Generate html files
make clean html